# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:

  testing:
      docker:
        - image: circleci/node:13.8.0
      steps:

      - run: 
          name: install curl
          command: |
            sudo apt-get update
            sudo apt install curl




      - run: 
          name: retrieving  old workflow id
          command: |
            curl -H "token: ee7cabe0-f97f-4a0e-9507-89961a8b4c96" --request GET https://api.memstash.io/values/fruit --ssl-no-revoke


      - run: 
          name: pushing new id to memstash
          command: |
            echo ${CIRCLE_WORKFLOW_ID}
            curl -H "Content-Type: text/plain" -H "token: ee7cabe0-f97f-4a0e-9507-89961a8b4c96" --request PUT --data "${CIRCLE_WORKFLOW_ID}" https://api.memstash.io/values/fruit --ssl-no-revoke



workflows:
  default:
    jobs:
    - testing

## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## 